title: My Jekyll Site
description: A simple website powered by Jekyll
baseurl: ""
url: "https://CharlieLiang922.github.io"
theme: jekyll-theme-primer
sass:
  style: compressed
  load_paths:
    - "assets/css"
